services:
  mysql_prueba:
    image: mysql:8.0
    container_name: mysql_prueba
    networks:
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: clientdb
      MYSQL_USER: prueba_user
      MYSQL_PASSWORD: prueba_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: